security:
  basic:
    enabled: false

---

spring:
  profiles: local
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

server:
  port: 8000

secretMessage: "Local Message"
